#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Snakemake file to run all the files within the pipeline

@author: portae1
"""
rule read_data:
    input:
        input_file="subjects.txt"
    output:
        output_file="eeg_tmp_data.pickle"
    params:
        arg1="task",
        arg2="normalization"
    shell:
        "python3 01_read_processed_data.py --arg1 {params.arg1} --arg2 {params.arg2} {input.input_file} > {output.output_file}"

rule rule2:
    input:
        input_file="path/to/input/file2",
        output_file="path/to/output/file1"
    output:
        output_file="path/to/output/file2"
    params:
        arg3="value3",
        arg4="value4"
    shell:
        "python script2.py --arg3 {params.arg3} --arg4 {params.arg4} {input.input_file} > {output.output_file}"
